# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"I\n\x08UserData\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x10\n\x08username\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t2?\n\x08UserAuth\x12\x33\n\x0bVerifyToken\x12\x13.users.TokenRequest\x1a\x0f.users.UserDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENREQUEST']._serialized_start=22
  _globals['_TOKENREQUEST']._serialized_end=51
  _globals['_USERDATA']._serialized_start=53
  _globals['_USERDATA']._serialized_end=126
  _globals['_USERAUTH']._serialized_start=128
  _globals['_USERAUTH']._serialized_end=191
# @@protoc_insertion_point(module_scope)
